In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/train.csv")

df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [2]:
cat_cols = [
    'Gender',
    'Married',
    'Dependents',
    'Self_Employed',
    'Education',
    'Property_Area'
]

num_cols = [
    'ApplicantIncome',
    'CoapplicantIncome',
    'LoanAmount',
    'Loan_Amount_Term',
    'Credit_History'
]

In [5]:
for col in cat_cols:
    df[col]=df[col].fillna(
        df[col].mode()[0]
    )

for col in num_cols:
    df[col]=df[col].fillna(
        df[col].median()
    )

In [7]:
#Feature Creation
df["TotalIncome"] = (
    df["ApplicantIncome"] +
    df["CoapplicantIncome"]
)

In [8]:
df["IncomePerPerson"] = (
    df["TotalIncome"] /
    (df["Dependents"]
      .replace("3+",3)
      .replace("0",1)
      .astype(int))
)

In [9]:
df["LoanIncomeRatio"] = (
    df["LoanAmount"] /
    df["TotalIncome"]
)

In [13]:
# Label Encoding
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in df.columns:
    if df[col].dtype == "str":
        df[col] = le.fit_transform(df[col])

In [17]:
df['Dependents'].value_counts()

Dependents
0    360
1    102
2    101
3     51
Name: count, dtype: int64

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    int64
 1   Gender             614 non-null    int64
 2   Married            614 non-null    int64
 3   Dependents         614 non-null    int64
 4   Education          614 non-null    int64
 5   Self_Employed      614 non-null    int64
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         614 non-null    float64
 9   Loan_Amount_Term   614 non-null    float64
 10  Credit_History     614 non-null    float64
 11  Property_Area      614 non-null    int64
 12  Loan_Status        614 non-null    int64
 13  TotalIncome        614 non-null    float64
 14  IncomePerPerson    614 non-null    float64
 15  LoanIncomeRatio    614 non-null    float64
dtypes: float64(7), int64(9)
memory usage: 76.9 KB

In [16]:
df.sample(10)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,TotalIncome,IncomePerPerson,LoanIncomeRatio
62,62,1,1,0,1,1,2609,3449.0,165.0,180.0,0.0,0,0,6058.0,6058.0,0.027237
243,243,1,1,2,0,1,6250,1300.0,108.0,360.0,1.0,0,1,7550.0,3775.0,0.014305
294,294,1,1,0,0,0,2383,3334.0,172.0,360.0,1.0,1,1,5717.0,5717.0,0.030086
378,378,1,0,0,0,0,3069,0.0,71.0,480.0,1.0,2,0,3069.0,3069.0,0.023135
516,516,0,1,2,0,0,2031,1632.0,113.0,480.0,1.0,1,1,3663.0,1831.5,0.030849
223,223,1,1,0,0,0,7578,1010.0,175.0,360.0,1.0,1,1,8588.0,8588.0,0.020377
531,531,1,1,3,0,0,4281,0.0,100.0,360.0,1.0,2,1,4281.0,1427.0,0.023359
80,80,0,0,0,0,0,3846,0.0,111.0,360.0,1.0,1,1,3846.0,3846.0,0.028861
274,274,1,1,2,0,0,3900,0.0,90.0,360.0,1.0,1,1,3900.0,1950.0,0.023077
406,406,1,1,0,1,0,2167,2400.0,115.0,360.0,1.0,2,1,4567.0,4567.0,0.025181

In [18]:
df.to_csv(
    "../data/processed/clean_loan_data.csv",
    index=False
)